const seedFoods = [
  { id: 'egg', name: 'Ägg, kokt', kcal: 143, protein: 12.6, carbs: 0.7, fat: 9.5 },
  { id: 'banana', name: 'Banan, utan skal', kcal: 89, protein: 1.1, carbs: 22.8, fat: 0.3 },
  { id: 'rice', name: 'Ris, kokt', kcal: 130, protein: 2.7, carbs: 28.2, fat: 0.3 },
  { id: 'rice-dry', name: 'Ris, okokt', kcal: 350, protein: 7.1, carbs: 78.9, fat: 0.7 },
  { id: 'chicken', name: 'Kycklingfilé, rå', kcal: 110, protein: 23.1, carbs: 0, fat: 1.2 },
  { id: 'oats', name: 'Havregryn', kcal: 360, protein: 13.3, carbs: 57, fat: 6.5 },
  { id: 'potato', name: 'Potatis, kokt', kcal: 80, protein: 1.8, carbs: 17, fat: 0.1 }
];
const OFF_FIELDS='code,product_name,product_name_sv,brands,quantity,serving_size,nutriments,image_front_small_url,countries_tags';
const OFF_HEADERS={'User-Agent':'Kalorier/1.0 (Cloudflare Worker)'};
function normalize(text){return String(text||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/coca[-\s]?cola/g,'coca cola').replace(/zero sugar/g,'zero').replace(/sugarfree|sockerfri/g,'zero').replace(/\bcoke\b/g,'coca cola').replace(/[^\p{L}\p{N}\s]+/gu,' ').replace(/\s+/g,' ').trim();}
function editDistance(a,b){if(a===b)return 0;if(!a||!b)return Math.max(a.length,b.length);if(Math.abs(a.length-b.length)>2)return 99;let prev=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const row=[i];for(let j=1;j<=b.length;j++)row[j]=Math.min(row[j-1]+1,prev[j]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));prev=row}return prev[b.length]}
function tokenMatch(token,candidate){if(candidate===token)return 100;if(candidate.startsWith(token))return 75;if(token.length>=4&&candidate.length>=4&&editDistance(token,candidate)<=1)return 55;if(token.length>=5&&editDistance(token,candidate)<=2)return 30;return 0}
function scoreMatch(query,product){const q=normalize(query),name=normalize(product.name),brand=normalize(product.brand),quantity=normalize(product.quantity),text=[name,brand,quantity].filter(Boolean).join(' ');if(!q||!name)return -999;const qt=q.split(' ').filter(Boolean),nt=name.split(' ').filter(Boolean),bt=brand.split(' ').filter(Boolean);let score=0;if(name===q)score+=3000;if(name.startsWith(q))score+=1200;if(name.includes(` ${q}`))score+=900;if(name.includes(q))score+=450;if(brand===q)score+=800;if(brand.includes(q))score+=250;let matched=0;for(const token of qt){let best=0;for(const candidate of [...nt,...bt])best=Math.max(best,tokenMatch(token,candidate));if(best>0){matched++;score+=best}else if(token.length>=4&&text.includes(token))score+=15}if(matched<qt.length)return -999;if(qt.length>1)score+=matched*250;score-=Math.max(0,nt.length-qt.length)*20;if(qt.length===1&&/\b(hemgjord|hemlagad|recept|gryta|sås|pannkaka|panna)\b/.test(name)&&!name.startsWith(q))score-=180;return score}
function productFromOFF(p){const n=p?.nutriments||{};return{id:`off:${p.code}`,barcode:p.code||null,name:p.product_name_sv||p.product_name||'Okänd produkt',brand:p.brands||'',quantity:p.quantity||'',serving_size:p.serving_size||'',kcal:Number(n['energy-kcal_100g']??n['energy-kcal']??0),protein:Number(n['proteins_100g']??0),carbs:Number(n['carbohydrates_100g']??0),fat:Number(n['fat_100g']??0),image:p.image_front_small_url||null,source:'openfoodfacts'};}
async function searchOpenFoodFacts(q){const params=new URLSearchParams({search_terms:q,search_simple:'1',action:'process',json:'1',page_size:'60',page:'1',lc:'sv',cc:'se',fields:OFF_FIELDS});const r=await fetch(`https://world.openfoodfacts.org/cgi/search.pl?${params}`,{headers:OFF_HEADERS});if(!r.ok)throw new Error(`Open Food Facts ${r.status}`);const d=await r.json();return(d.products||[]).filter(p=>p.code&&(p.product_name_sv||p.product_name)).map(productFromOFF).filter(p=>p.kcal>0||p.protein>0||p.carbs>0||p.fat>0).map(p=>({...p,_score:scoreMatch(q,p)})).filter(p=>p._score>0).sort((a,b)=>b._score-a._score).slice(0,20).map(({_score,...p})=>p);}
async function getOpenFoodFactsProduct(barcode){const r=await fetch(`https://world.openfoodfacts.org/api/v2/product/${encodeURIComponent(barcode)}?fields=${OFF_FIELDS}`,{headers:OFF_HEADERS});if(!r.ok)throw new Error(`Open Food Facts ${r.status}`);const d=await r.json();return d.status===1&&d.product?productFromOFF(d.product):null;}
async function ensureDiary(env){if(!env.DB)return;await env.DB.prepare(`CREATE TABLE IF NOT EXISTS food_entries (id INTEGER PRIMARY KEY AUTOINCREMENT,date TEXT NOT NULL,time TEXT NOT NULL,name TEXT NOT NULL,source TEXT,product_id TEXT,barcode TEXT,grams REAL NOT NULL,kcal REAL NOT NULL,protein REAL NOT NULL,carbs REAL NOT NULL,fat REAL NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();}
function json(data,status=200){return Response.json(data,{status});}
export default {async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/api/health')return json({ok:true,service:'kalorier'});
if(url.pathname==='/api/diary'&&env.DB){await ensureDiary(env);if(request.method==='GET'){const date=url.searchParams.get('date')||new Date().toISOString().slice(0,10);const r=await env.DB.prepare(`SELECT * FROM food_entries WHERE date=? ORDER BY time ASC,id ASC`).bind(date).all();return json(r.results);}if(request.method==='POST'){let b;try{b=await request.json();}catch{return json({error:'Ogiltig JSON.'},400);}const date=String(b.date||new Date().toISOString().slice(0,10));const now=new Date();const time=String(b.time||now.toISOString().slice(11,16));const grams=Number(b.grams);if(!b.name||!Number.isFinite(grams)||grams<=0)return json({error:'Namn och mängd krävs.'},400);const r=await env.DB.prepare(`INSERT INTO food_entries(date,time,name,source,product_id,barcode,grams,kcal,protein,carbs,fat) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).bind(date,time,String(b.name),b.source||null,b.product_id||null,b.barcode||null,grams,Number(b.kcal)||0,Number(b.protein)||0,Number(b.carbs)||0,Number(b.fat)||0).run();return json({id:r.meta.last_row_id});}if(request.method==='PUT'||request.method==='PATCH'){let b;try{b=await request.json();}catch{return json({error:'Ogiltig JSON.'},400);}const id=Number(url.searchParams.get('id'));if(!id)return json({error:'ID saknas.'},400);await env.DB.prepare(`UPDATE food_entries SET date=?,time=?,name=?,grams=?,kcal=?,protein=?,carbs=?,fat=? WHERE id=?`).bind(String(b.date),String(b.time),String(b.name),Number(b.grams),Number(b.kcal)||0,Number(b.protein)||0,Number(b.carbs)||0,Number(b.fat)||0,id).run();return json({ok:true});}if(request.method==='DELETE'){const id=Number(url.searchParams.get('id'));if(!id)return json({error:'ID saknas.'},400);await env.DB.prepare(`DELETE FROM food_entries WHERE id=?`).bind(id).run();return json({ok:true});}}
if(url.pathname==='/api/foods'&&request.method==='GET'){const raw=String(url.searchParams.get('q')||'').trim();const q=normalize(raw);if(env.DB){try{const base=`SELECT id,name,category,kcal_per_100g AS kcal,protein_per_100g AS protein,carbs_per_100g AS carbs,fat_per_100g AS fat,edible_state,preparation,source,verified FROM foods`;const r=q?await env.DB.prepare(`${base} WHERE lower(replace(replace(replace(name,'å','a'),'ä','a'),'ö','o')) LIKE ? ORDER BY verified DESC,name LIMIT 80`).bind(`%${q}%`).all():await env.DB.prepare(`${base} ORDER BY verified DESC,name LIMIT 30`).all();return json(r.results);}catch(e){console.error(e);return json({error:'Kunde inte läsa livsmedelsdatabasen.'},502);}}return json(q?seedFoods.filter(f=>normalize(f.name).includes(q)):seedFoods);}
if(url.pathname==='/api/products'&&request.method==='GET'){const q=(url.searchParams.get('q')||'').trim();if(normalize(q).length<2)return json([]);try{return Response.json(await searchOpenFoodFacts(q),{headers:{'Cache-Control':'public,max-age=300'}});}catch(e){console.error(e);return json({error:'Kunde inte läsa produktdatabasen.'},502);}}
if(url.pathname.startsWith('/api/products/barcode/')&&request.method==='GET'){const barcode=url.pathname.split('/').pop();if(!/^\d{8,14}$/.test(barcode))return json({error:'Ogiltig streckkod.'},400);try{const p=await getOpenFoodFactsProduct(barcode);return p?json(p):json({error:'Produkten hittades inte.'},404);}catch(e){console.error(e);return json({error:'Kunde inte läsa produktdatabasen.'},502);}}
return env.ASSETS.fetch(request);}};